---
driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-6.0.8
  - name: debian-7.4
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: default
    run_list:
      - recipe[up2date]
    attributes: {}
